### ISSUE TITLE
简书移动端网页广告

### ISSUE THREAD

**Issue by yu22cOwO** [zzChumo/PillowDNS#1]
## 已知域名列表（使用X浏览器自带功能“查看页面资源”可见）
- sensors.ibreader.com
- qzs.gdtimg.com
- www.ahuano.com
- brssp.ibreader.com
- twlcyc.cn
- cdn.yeambin.com
- s1.hapying.com
- www.ilkwork.com

## 已知广告行为

在网页加上百度广告：

![Screenshot_2023-09-16-00-08-51-22_82b10d9f3584360f08225ddcebbb4f6d.jpg](https://github.com/zzChumo/PillowDNS/assets/116557254/c9e5590a-6c6e-4f1c-ac27-ce6224f92460)

高频率请求打开购物软件：

![Screenshot_2023-09-16-00-13-14-15_82b10d9f3584360f08225ddcebbb4f6d.jpg](https://github.com/zzChumo/PillowDNS/assets/116557254/3c41cab6-6277-43e5-8cc7-20ba9bb8ed63)

污染剪贴板：

![Screenshot_2023-09-16-00-10-13-99_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/zzChumo/PillowDNS/assets/116557254/29a34b56-2068-47e2-8479-771e88306666)

经过测试，已排除：
- 运营商劫持（运营商不会闲的没事解密VPN流量就为了加广告）
- DNS劫持（使用阿里DNS、Cloudflare DNS仍出现该情况）

**Comment by zzChumo** [comment]
收到，感谢反馈。

但以下网站我们将不会进行屏蔽处理，原因为疑似个人主页：
www.ilkwork.com
www.ahuano.com

**Comment by zzChumo** [comment]
我们目前已经将上次未屏蔽的域名全部屏蔽。

感谢您的支持。
